name: bug_33761_exp
version: 0.1.0
description: Showing dart2js bug
environment:
  sdk: '>=2.0.0-dev.63 <2.0.0'
dev_dependencies:
  test: '>=1.2.0'
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'