name: core_list_test
description: A sample Polymer application
dependencies:
  core_elements: any
  # polymer: '>=0.11.0-dev.2 <0.13.0'
  polymer: '>=0.13.0 <0.14.0'
transformers:
- polymer:
    entry_points: web/core_list_dart.html
